export const LAST_WORKSPACE = "LAST_WORKSPACE"
export const WORKSPACE = "WORKSPACE"
export const CURRENTWORKSPACE = 'CURRENTWORKSPACE'
export const CURRENTWORKSPACEBOARDS = "CURRENTWORKSPACEBOARDS"
export const LOADWORKSPACE = "LOADWORKSPACE"